[tox]
minversion = 4
requires =
  pip >= 24.0
  uv >= 0.8.0
  tox-uv >= 1.15.0
envlist =
  py311
  py312

[testenv]
setenv =
  PIP_INDEX_URL = {env:PIP_INDEX_URL:https://artifactory.spotify.net/artifactory/api/pypi/pypi/simple/}
  UV_DEFAULT_INDEX = {env:PIP_INDEX_URL:https://artifactory.spotify.net/artifactory/api/pypi/pypi/simple/}
  SETUPTOOLS_SCM_PRETEND_VERSION = {env:SETUPTOOLS_SCM_PRETEND_VERSION:0.0.0}
runner = uv-venv-lock-runner
package = editable

[testenv:{py311,py312}]
extras = dev
commands =
  pytest {posargs:tests/ -x -q}
